# Generated by Django 4.2 on 2023-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["username"],
                "verbose_name": "cook",
                "verbose_name_plural": "cooks",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
