# Generated by Django 4.2 on 2023-04-13 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["username"],
                "verbose_name": "cook",
                "verbose_name_plural": "cooks",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["-id"]},
        ),
    ]
